#!/bin/sh
# Copyright 2019 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This files wraps lld.
# Pass --hash-style=gnu to match gold/bfd wrappers.

exec "$(dirname "$(readlink -f "$0")")"/ld.lld --hash-style=gnu -z nostart-stop-gc "$@"
